package view;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ganda Kurniawan
 */
public class v_compare extends javax.swing.JFrame {

    /**
     * Creates new form v_compare
     */
    public v_compare() {
        initComponents();
    }
    
    public void keluar (ActionListener action) {
        btnlogout.addActionListener(action);
    }
    
    public void masuk (ActionListener action) {
        dashboard.addActionListener(action);
    }
    
    public void profile (ActionListener action){
        profile.addActionListener(action);
    }
    
    public void konsultasi (ActionListener ation){
        konsultasi.addActionListener(ation);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listproduk = new javax.swing.JComboBox();
        listproduk2 = new javax.swing.JComboBox();
        btnlogout = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dashboard = new javax.swing.JButton();
        compare = new javax.swing.JButton();
        konsultasi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listproduk.setBackground(new java.awt.Color(153, 153, 153));
        listproduk.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        listproduk.setForeground(new java.awt.Color(255, 255, 255));
        listproduk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Produk 1", "Produk 2", "Produk 3", "Produk 4" }));
        listproduk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listprodukActionPerformed(evt);
            }
        });
        jPanel1.add(listproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 110, -1));

        listproduk2.setBackground(new java.awt.Color(153, 153, 153));
        listproduk2.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        listproduk2.setForeground(new java.awt.Color(255, 255, 255));
        listproduk2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Produk 2", "Produk 3", "Produk 4", "Produk 5", " " }));
        listproduk2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listproduk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listproduk2ActionPerformed(evt);
            }
        });
        jPanel1.add(listproduk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 110, -1));

        btnlogout.setBackground(new java.awt.Color(148, 188, 241));
        btnlogout.setFont(new java.awt.Font("Poppins SemiBold", 1, 10)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 50, 30));

        profile.setBackground(new java.awt.Color(0, 51, 51));
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/profile.png"))); // NOI18N
        profile.setBorder(null);
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 30, 30));

        jPanel2.setBackground(new java.awt.Color(228, 228, 228));

        dashboard.setBackground(new java.awt.Color(228, 228, 228));
        dashboard.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(0, 51, 51));
        dashboard.setText("Dashboard");
        dashboard.setBorder(null);

        compare.setBackground(new java.awt.Color(228, 228, 228));
        compare.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        compare.setForeground(new java.awt.Color(0, 51, 51));
        compare.setText("Compare");
        compare.setBorder(null);

        konsultasi.setBackground(new java.awt.Color(228, 228, 228));
        konsultasi.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        konsultasi.setForeground(new java.awt.Color(0, 51, 51));
        konsultasi.setText("Konsultasi");
        konsultasi.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compare, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(konsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(compare, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(konsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 160, 210));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/6. NARUKO Tea Tree Shine Control & Blemish Clear Mask.jpg"))); // NOI18N
        jLabel2.setText("\\");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 110, -1));

            jPanel4.setBackground(new java.awt.Color(255, 255, 255));

            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/12. JOYLAB Berry Bounce Facial Toner.jpg"))); // NOI18N

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 110, -1));

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/compare.png"))); // NOI18N
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            setSize(new java.awt.Dimension(796, 539));
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void listprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listprodukActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void listproduk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listproduk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listproduk2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_compare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_compare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_compare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_compare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_compare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton compare;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton konsultasi;
    private javax.swing.JComboBox listproduk;
    private javax.swing.JComboBox listproduk2;
    private javax.swing.JButton profile;
    // End of variables declaration//GEN-END:variables
}
