/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Ganda Kurniawan
 */
public class v_dashdokter extends javax.swing.JFrame {

    /**
     * Creates new form v_dashdokter
     */
    public v_dashdokter() {
        initComponents();
    }
    
     public void keluar (ActionListener action) {
        btnlogout.addActionListener(action);
    }
    
    public void profile (ActionListener action){
        profile.addActionListener(action);
    }
    
    public void konsultasidokter (ActionListener action){
        konsultasi.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profile = new javax.swing.JButton();
        read = new javax.swing.JButton();
        read1 = new javax.swing.JButton();
        read2 = new javax.swing.JButton();
        read3 = new javax.swing.JButton();
        read5 = new javax.swing.JButton();
        read4 = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dashboard = new javax.swing.JButton();
        konsultasi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setBackground(new java.awt.Color(0, 51, 51));
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/profile.png"))); // NOI18N
        profile.setBorder(null);
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 30, 30));

        read.setBackground(new java.awt.Color(0, 51, 51));
        read.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        read.setForeground(new java.awt.Color(255, 255, 255));
        read.setText("Read more");
        read.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });
        jPanel1.add(read, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 90, 20));

        read1.setBackground(new java.awt.Color(0, 51, 51));
        read1.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        read1.setForeground(new java.awt.Color(255, 255, 255));
        read1.setText("Read more");
        read1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        read1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read1ActionPerformed(evt);
            }
        });
        jPanel1.add(read1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 90, 20));

        read2.setBackground(new java.awt.Color(0, 51, 51));
        read2.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        read2.setForeground(new java.awt.Color(255, 255, 255));
        read2.setText("Read more");
        read2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        read2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read2ActionPerformed(evt);
            }
        });
        jPanel1.add(read2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 90, 20));

        read3.setBackground(new java.awt.Color(0, 51, 51));
        read3.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        read3.setForeground(new java.awt.Color(255, 255, 255));
        read3.setText("Read more");
        read3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        read3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read3ActionPerformed(evt);
            }
        });
        jPanel1.add(read3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 90, 20));

        read5.setBackground(new java.awt.Color(0, 51, 51));
        read5.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        read5.setForeground(new java.awt.Color(255, 255, 255));
        read5.setText("Read more");
        read5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        read5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read5ActionPerformed(evt);
            }
        });
        jPanel1.add(read5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 90, 20));

        read4.setBackground(new java.awt.Color(0, 51, 51));
        read4.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        read4.setForeground(new java.awt.Color(255, 255, 255));
        read4.setText("Read more");
        read4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        read4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read4ActionPerformed(evt);
            }
        });
        jPanel1.add(read4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 90, 20));

        btnlogout.setBackground(new java.awt.Color(148, 188, 241));
        btnlogout.setFont(new java.awt.Font("Poppins SemiBold", 1, 10)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 50, 30));

        jPanel2.setBackground(new java.awt.Color(228, 228, 228));

        dashboard.setBackground(new java.awt.Color(228, 228, 228));
        dashboard.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(0, 51, 51));
        dashboard.setText("Dashboard");
        dashboard.setBorder(null);

        konsultasi.setBackground(new java.awt.Color(228, 228, 228));
        konsultasi.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        konsultasi.setForeground(new java.awt.Color(0, 51, 51));
        konsultasi.setText("Konsultasi");
        konsultasi.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(konsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(konsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 160, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/dashboard.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileActionPerformed

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readActionPerformed

    private void read1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read1ActionPerformed

    private void read2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read2ActionPerformed

    private void read3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read3ActionPerformed

    private void read5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read5ActionPerformed

    private void read4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read4ActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_dashdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_dashdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_dashdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_dashdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_dashdokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton konsultasi;
    private javax.swing.JButton profile;
    private javax.swing.JButton read;
    private javax.swing.JButton read1;
    private javax.swing.JButton read2;
    private javax.swing.JButton read3;
    private javax.swing.JButton read4;
    private javax.swing.JButton read5;
    // End of variables declaration//GEN-END:variables
}
