/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Ganda Kurniawan
 */
public class v_pilihdurasi extends javax.swing.JFrame {

    /**
     * Creates new form v_pilihdurasi
     */
    public v_pilihdurasi() {
        initComponents();
    }
    
    public void back (ActionListener action){
        back.addActionListener(action);
    }
    
    public void pilih (ActionListener action){
        pilih.addActionListener(action);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pilih = new javax.swing.JButton();
        back = new javax.swing.JButton();
        durasi1 = new javax.swing.JCheckBox();
        durasi2 = new javax.swing.JCheckBox();
        durasi3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pilih.setBackground(new java.awt.Color(148, 188, 241));
        pilih.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        pilih.setForeground(new java.awt.Color(255, 255, 255));
        pilih.setText("Pilih Durasi");
        pilih.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 100, 40));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/arrow.png"))); // NOI18N
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 30, 30));

        durasi1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        durasi1.setForeground(new java.awt.Color(0, 51, 51));
        durasi1.setText("30 Menit");
        durasi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        durasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durasi1ActionPerformed(evt);
            }
        });
        jPanel1.add(durasi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 280, 50));

        durasi2.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        durasi2.setForeground(new java.awt.Color(0, 51, 51));
        durasi2.setText("60 Menit");
        durasi2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        durasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durasi2ActionPerformed(evt);
            }
        });
        jPanel1.add(durasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 280, 50));

        durasi3.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        durasi3.setForeground(new java.awt.Color(0, 51, 51));
        durasi3.setText("90 Menit");
        durasi3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        durasi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durasi3ActionPerformed(evt);
            }
        });
        jPanel1.add(durasi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dekstop Pilih Durasi.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(796, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void durasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durasi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durasi1ActionPerformed

    private void durasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durasi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durasi2ActionPerformed

    private void durasi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durasi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durasi3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_pilihdurasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_pilihdurasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_pilihdurasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_pilihdurasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_pilihdurasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JCheckBox durasi1;
    private javax.swing.JCheckBox durasi2;
    private javax.swing.JCheckBox durasi3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pilih;
    // End of variables declaration//GEN-END:variables
}
